# Generated by Django 4.0.3 on 2022-04-04 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Case_Name', models.CharField(max_length=50, verbose_name='Название кейса')),
                ('Case_Comment', models.TextField(verbose_name='Коментарий')),
                ('Is_Pattern', models.BooleanField(default=False, verbose_name='Шаблон')),
                ('Is_Pattern_For_Teacher', models.BooleanField(default=False, verbose_name='Шаблон для преподавателя')),
                ('Is_Ready', models.BooleanField(default=False, verbose_name='Готов к использованию')),
                ('Case_Title', models.TextField(verbose_name='Наименование;ИНН')),
                ('Case_Location', models.TextField(verbose_name='Год основания, месторасположения')),
                ('Case_Type_of_activity', models.TextField(verbose_name='Основные виды деятельности')),
                ('Case_Production', models.TextField(verbose_name='Выпускаемая продукция')),
            ],
            options={
                'verbose_name': 'Кейс',
                'verbose_name_plural': 'Кейсы',
            },
        ),
        migrations.CreateModel(
            name='CaseParametr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Param_Name', models.CharField(max_length=200, verbose_name='Название параметра')),
                ('Param_Comment', models.TextField(verbose_name='Коментарий')),
                ('Name_Variable', models.CharField(blank=True, max_length=20, null=True, verbose_name='Имя переменной')),
                ('Formula', models.TextField(blank=True, null=True, verbose_name='Формула для вычисления этого параметра')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
            ],
            options={
                'verbose_name': 'Параметр кейса',
                'verbose_name_plural': 'Параметры кейсов',
            },
        ),
    ]
