# Generated by Django 4.0.3 on 2022-04-05 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_rename_dateparam_dateparametr_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFile',
        ),
    ]
